version: "3"

services:
  db:
    image: neo4j:latest
    volumes:
      - $HOME/neo4j/data:/data \
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env

  server:
    image: mohamedazab/family-tree-server:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./familyTreeWeb/.env
    depends_on:
      - db
