name: Django CI

# workflow trigger
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1 # action to setup python development
        with:
          python-version: ${{ matrix.python-version }} # version selected from the specified matrix

      - name: Install Dependencies
        run: | # multi line run
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

  publish:
    needs: build
    runs-on:ubuntu-latest
    steps:
      - name: build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: login to  Docker Hub
        run: docker login -u DOCKERHUB_USERNAME -p DOCKERHUB_PASS
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}


      - name: publish to Docker Hub
        run: docker push $IMAGE_NAME:latest
        env:
          IMAGE_NAME: mohamedazab/family-tree-server
